# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='profitLoss',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
